management:
  endpoints:
    web:
      exposure:
        include: beans,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
server:
  port : 666